package www.user.com.bean;

import java.io.Serializable;

public class F_Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_role.rid
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_role.rname
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private String rname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_role.rid
     *
     * @return the value of f_role.rid
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_role.rid
     *
     * @param rid the value for f_role.rid
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_role.rname
     *
     * @return the value of f_role.rname
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_role.rname
     *
     * @param rname the value for f_role.rname
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", rname=").append(rname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}