package www.user.com.bean;

import java.io.Serializable;

public class T_area implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.areaId
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.areaCode
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.areaName
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.level
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.cityCode
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.center
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private String center;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.parentId
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.areaId
     *
     * @return the value of t_area.areaId
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.areaId
     *
     * @param areaid the value for t_area.areaId
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.areaCode
     *
     * @return the value of t_area.areaCode
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.areaCode
     *
     * @param areacode the value for t_area.areaCode
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.areaName
     *
     * @return the value of t_area.areaName
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.areaName
     *
     * @param areaname the value for t_area.areaName
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.level
     *
     * @return the value of t_area.level
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.level
     *
     * @param level the value for t_area.level
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.cityCode
     *
     * @return the value of t_area.cityCode
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.cityCode
     *
     * @param citycode the value for t_area.cityCode
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.center
     *
     * @return the value of t_area.center
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.center
     *
     * @param center the value for t_area.center
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setCenter(String center) {
        this.center = center == null ? null : center.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.parentId
     *
     * @return the value of t_area.parentId
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.parentId
     *
     * @param parentid the value for t_area.parentId
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areaid=").append(areaid);
        sb.append(", areacode=").append(areacode);
        sb.append(", areaname=").append(areaname);
        sb.append(", level=").append(level);
        sb.append(", citycode=").append(citycode);
        sb.append(", center=").append(center);
        sb.append(", parentid=").append(parentid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}