package www.user.com.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import www.user.com.bean.F_Role;
import www.user.com.bean.F_RoleExample;

@Mapper
public interface F_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    long countByExample(F_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int deleteByExample(F_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int insert(F_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int insertSelective(F_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    List<F_Role> selectByExample(F_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    F_Role selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") F_Role record, @Param("example") F_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByExample(@Param("record") F_Role record, @Param("example") F_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByPrimaryKeySelective(F_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_role
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByPrimaryKey(F_Role record);
}