package www.user.com.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import www.user.com.bean.F_User;
import www.user.com.bean.F_UserExample;

@Mapper
public interface F_UserMapper {

    List<F_User> queryAllDataFromTable(@Param("page") int page, @Param("limit") int limit, @Param("keyWord") String keyWord);

    int queryAllCount(String keyWord);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    long countByExample(F_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int deleteByExample(F_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int insert(F_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int insertSelective(F_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    List<F_User> selectByExample(F_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    F_User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") F_User record, @Param("example") F_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int updateByExample(@Param("record") F_User record, @Param("example") F_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int updateByPrimaryKeySelective(F_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @mbg.generated Wed May 22 11:49:18 CST 2019
     */
    int updateByPrimaryKey(F_User record);
}