package www.user.com.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import www.user.com.bean.T_area;
import www.user.com.bean.T_areaExample;

@Mapper
public interface T_areaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    long countByExample(T_areaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int deleteByExample(T_areaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int deleteByPrimaryKey(Integer areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int insert(T_area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int insertSelective(T_area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    List<T_area> selectByExample(T_areaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    T_area selectByPrimaryKey(Integer areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") T_area record, @Param("example") T_areaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByExample(@Param("record") T_area record, @Param("example") T_areaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByPrimaryKeySelective(T_area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbg.generated Tue May 21 21:08:37 CST 2019
     */
    int updateByPrimaryKey(T_area record);
}